### PR TITLE
Fix Google Maps options.

### PR DESCRIPTION
**Pull request by diskshima**
* Only use the default value if the value was undefined.

### CODE REVIEW

**Comment by amenadiel** [comment]
I agree in that using

```
instance.parameter = options.parameter || true;
```

is wrong, because if you explicitly set options.parameter to `false`, instance.parameter will still be true.

However, it doesn't sound like a great idea to declare `valueOrDefault` as a global variable. You could as well declare `valueOrDefault` inside GMaps constructor.

**Comment by diskshima** [comment]
> However, it doesn't sound like a great idea to declare valueOrDefault as a global variable. You could as well declare valueOrDefault inside GMaps constructor.

Very true. Let me rewrite it and push again.

**Comment by diskshima** [comment]
@amenadiel 
Moved the `valueOrDefault` method into the constructor.

**Comment by hpneo** [comment]
Please move this function to `gmaps.core.js`. `gmaps.js` is just a autogenerated bundle.

**Comment by diskshima** [comment]
I've issued a new pull request for this as master hand moved on quite a bit.
New pull request is #425

**Pull request closed without merging**
