### PR TITLE
Do not check for the window.google.maps library

### PR DESCRIPTION
**Pull request by adelamarre**
This check just dont let us load gmaps.js before the load of the google maps library.
we can not use the bower package google-maps (https://libraries.io/bower/google-maps) to lazy load the google.maps library with bower.

### CODE REVIEW

**Comment by adelamarre** [comment]
Here is how i would use Gmaps : 

```javascript
window.GoogleMapsLoader.load(function(google){
        map = new GMaps({ el: '#map-container' });
        ...
});
```
But the check avoids this possibility because at this time Gmaps is an empty function.
You may want Gmaps to check for the presence of the window.GoogleMapsLoader but I think this will be too restrictive and will not ensure that google.maps is loaded.

**Comment by hpneo** [comment]
Have you tried to move that code to the line 152, just after the GMaps constructor? I prefer to maintain the checking code because some people think GMaps already loads Google Maps API.

**Comment by adelamarre** [comment]
Thanks for reply. No, I do not want to change the source of the package because i manage everything with bower and grunt. But we could imagine an other solution to avoid this test ? 
It will preserve the warning for new users and let us use your library in continuous integration/deployment process.

**Comment by hpneo** [comment]
Sorry, I meant the code you are changing in the pull request. Instead of removing the checking and warning in `gmaps.core.js`, move to the linea 152 in the same file. That way, when someone tries to create a map, it will check if Google Maps is already loaded.

**Comment by adelamarre** [comment]
Ok, sorry. It's done and working for me. Tests are passed too. Please, could you merge this PR ?

**Comment by hpneo** [comment]
Thanks for the PR! It's merged now.

**Pull request merged**
